<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta name="viewport" content="width=device-width, initial-scale=0.5">
<title>Untitled Document</title>
</head>

<body>
<table border="1">
<tr>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
<td>ABC</td>
</tr>
<tr>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
<td>XYZ</td>
</tr>

</body>
</html>
